### ISSUE TITLE
0xc000007b

### ISSUE THREAD

**Issue by DLewis13** [xsacha/Sachesi#85] opened 2015-12-25 11:20 UTC
2.0.3 failed to start, error 0xc000007b.
Ran sfc /scannow in Command Prompt, nothing to fix.
Searches do not help.
Running Window 7 SP1 Ultimate.

Thanks, Dick Lewis

**Comment by DLewis13** [comment] 2016-01-18 22:37
Looks like you need vc_redist.x86.exe, I had x64 installed.
After installing x86 version, 2.0.3 works fine.
Link to Microsoft site:

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by jbuc89** [comment] 2016-01-20 23:55
The link above was for Visual C++ Redistributable for Visual Studio 2015 and did not work on my Windows 7 installation.

Here is the link for Visual C++ Redistributable Packages for Visual Studio 2013 which did work for Windows 7 and also go rid of the "MSVCR120.dll missing error message":

https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by DLewis13** [comment] 2016-01-22 11:58
Worked on mine, I already had the other versions installed. Including 2008, 2010, 2012 and 2013.
I only posted my final step, everyone's configuration is different.

**Comment by christinegrant98** [comment] 2017-01-24 12:29
just google the issue and found this guide to fix Error Code 0xc000007b worked for me as i have faced the same problem.
[http://errorcodespro.com/fix-error-code-0xc000007b-windows-7-10/](http://errorcodespro.com/fix-error-code-0xc000007b-windows-7-10/)

**Comment by xsacha** [comment] 2018-05-12 13:30
Duplicate of #62

**Closed by xsacha** 2018-05-12 13:30 UTC
